const constants = require("../constants/constants");
const {
  REQUEST_TYPE_REQUESTED,
  REQUEST_TYPE_CANCELLED,
  REQUEST_TYPE_REJECTED,
  REQUEST_TYPE_GAVE,
  REQUEST_TYPE_RETURNED
} = constants;

exports.REQUEST_TYPES = [
  REQUEST_TYPE_REQUESTED,
  REQUEST_TYPE_CANCELLED,
  REQUEST_TYPE_REJECTED,
  REQUEST_TYPE_GAVE,
  REQUEST_TYPE_RETURNED
];

exports.OWNER_ONLY_TRANSACTIONS = [REQUEST_TYPE_REJECTED, REQUEST_TYPE_GAVE];

exports.REQUEST_TRANSITIONS = {
  [REQUEST_TYPE_REQUESTED]: [
    REQUEST_TYPE_CANCELLED,
    REQUEST_TYPE_REJECTED,
    REQUEST_TYPE_GAVE
  ],
  [REQUEST_TYPE_CANCELLED]: [REQUEST_TYPE_REQUESTED],
  [REQUEST_TYPE_REJECTED]: [REQUEST_TYPE_REQUESTED],
  [REQUEST_TYPE_GAVE]: [REQUEST_TYPE_RETURNED],
  [REQUEST_TYPE_RETURNED]: []
};

exports.OTP_REQUIRED = [REQUEST_TYPE_GAVE, REQUEST_TYPE_RETURNED];
